# Generated by Django 4.1.7 on 2023-03-18 00:31

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/Images')),
                ('is_star', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='static/Images')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/Images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('short_desc', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hot', models.IntegerField(blank=True, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.topic')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.type')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'news',
            },
        ),
    ]
