# Generated by Django 4.1.7 on 2023-03-29 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_alter_news_image_alter_news_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_hot',
        ),
        migrations.AddField(
            model_name='news',
            name='author_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
