# Generated by Django 4.1.7 on 2023-03-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_news_is_hot_news_author_id_news_is_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_by',
        ),
    ]
