# Generated by Django 4.1.7 on 2023-04-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=12, upload_to='photos/post/news'),
            preserve_default=False,
        ),
    ]
