# Generated by Django 4.1.7 on 2023-03-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',), 'verbose_name': 'review', 'verbose_name_plural': 'comments'},
        ),
    ]
