# Generated by Django 4.1.7 on 2023-03-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='new_id',
            new_name='news_id',
        ),
    ]
