# Generated by Django 4.1.7 on 2023-03-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('review', '0003_rename_new_id_comment_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.news'),
        ),
    ]
