# Generated by Django 4.1.7 on 2023-03-22 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_comment_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/Images'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/static/Images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
